"""Build art/characters/index.html — visual dashboard of every runtime sheet.

For every character × pass:
  - 4× zoom thumbnail of the runtime sheet
  - status (PASS/FAIL/MISSING)
  - color count, dimensions
  - GIF previews if present

Usage (via CLI dispatcher):
  ./sprite catalog
"""
from __future__ import annotations

import html
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

from _common import (  # noqa: E402
    ART_ROOT,
    list_specs, load_spec,
    green, dim, header, relpath,
)
from palette import by_name  # noqa: E402
from validate_sprite import validate_runtime_sheet  # noqa: E402


CSS = """
body { font-family: 'EB Garamond', Garamond, serif; background: #efe6d0; color: #1a1612; margin: 0; padding: 24px 32px; }
h1 { font-size: 28px; font-weight: 400; margin: 0 0 4px 0; }
.sub { color: #6b6358; font-style: italic; margin-bottom: 28px; }
.character { margin: 32px 0; }
.character h2 { font-size: 20px; font-weight: 400; border-bottom: 1px solid rgba(26,22,18,0.18); padding-bottom: 4px; }
.passes { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 18px; }
.pass { background: #f6f1e0; border: 1px solid rgba(26,22,18,0.18); padding: 14px 16px; box-shadow: 0 1px 0 rgba(26,22,18,0.08), 0 2px 6px rgba(26,22,18,0.06); }
.pass h3 { font-size: 15px; margin: 0 0 6px 0; font-weight: 600; }
.pass .meta { font-family: 'IBM Plex Mono', monospace; font-size: 10px; color: #6b6358; letter-spacing: 0.04em; text-transform: uppercase; }
.pass .status-PASS { color: #5a6b48; font-weight: 600; }
.pass .status-FAIL { color: #8a2018; font-weight: 600; }
.pass .status-MISSING { color: #6b6358; font-style: italic; }
.pass img { display: block; max-width: 100%; image-rendering: pixelated; image-rendering: crisp-edges; margin: 10px 0; background: rgba(91,103,112,0.08); border: 1px solid rgba(26,22,18,0.08); }
.pass .gifs { display: flex; gap: 8px; flex-wrap: wrap; }
.pass .gifs figure { margin: 0; text-align: center; }
.pass .gifs img { width: 96px; height: auto; image-rendering: pixelated; }
.pass .gifs figcaption { font-family: 'IBM Plex Mono', monospace; font-size: 9px; color: #6b6358; margin-top: 2px; letter-spacing: 0.04em; text-transform: uppercase; }
.pass .desc { color: #2b2520; font-size: 13px; margin: 6px 0 0; }
footer { color: #6b6358; font-style: italic; font-size: 12px; margin-top: 36px; border-top: 1px solid rgba(26,22,18,0.18); padding-top: 14px; }
"""


def _validate_terse(character: str, pass_name: str) -> tuple[str, dict]:
    spec = load_spec(character)
    rt = spec.runtime_path(pass_name)
    if not rt.exists():
        return ("MISSING", {})
    try:
        report = validate_runtime_sheet(
            path=rt,
            expected_w=spec.sheet_w(pass_name),
            expected_h=spec.sheet_h(pass_name),
            palette=by_name(spec.palette),
            frame_w=spec.frame_w(pass_name),
            frame_h=spec.frame_h(pass_name),
            baseline_y=spec.baseline_y(pass_name),
            target_cols=spec.target_cols(pass_name),
            target_rows=spec.target_rows(pass_name),
        )
        return ("PASS" if report.ok else "FAIL", report.stats)
    except Exception:
        return ("FAIL", {})


def _href_for(p: Path, anchor: Path) -> str:
    """Path relative to the HTML file's directory."""
    try:
        return str(Path(p).resolve().relative_to(anchor.resolve()))
    except ValueError:
        return f"file://{p}"


def run() -> int:
    out_path = ART_ROOT / "index.html"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    parts: list[str] = []
    parts.append("<!doctype html><html lang=\"en\"><head>")
    parts.append("<meta charset=\"utf-8\">")
    parts.append("<title>Tincture of Mercy — sprite catalog</title>")
    parts.append("<link rel=\"stylesheet\" href=\"../../design_system/colors_and_type.css\">")
    parts.append(f"<style>{CSS}</style>")
    parts.append("</head><body>")
    parts.append("<h1>Sprite Catalog</h1>")
    parts.append("<div class=\"sub\">Generated by <code>./sprite catalog</code> — every character × pass with current acceptance.</div>")

    for character in list_specs():
        spec = load_spec(character)
        parts.append(f"<section class=\"character\"><h2>{html.escape(character)} <span class=\"meta\">palette: {spec.palette}</span></h2>")
        parts.append("<div class=\"passes\">")
        for pass_name in spec.passes:
            pass_spec = spec.passes[pass_name]
            status, stat = _validate_terse(character, pass_name)
            rt = spec.runtime_path(pass_name)
            zoom = spec.preview_dir() / f"{spec.name}_{pass_name}_{spec.canvas_label(pass_name)}_zoom4x.png"
            anchor = out_path.parent

            parts.append("<div class=\"pass\">")
            parts.append(f"<h3>{html.escape(pass_name)} <span class=\"meta status-{status}\">{status}</span></h3>")
            desc = pass_spec.get("description", "")
            if desc:
                parts.append(f"<div class=\"desc\">{html.escape(desc)}</div>")
            meta_bits = [
                f"{spec.target_cols(pass_name)}×{spec.target_rows(pass_name)} cells",
                f"{spec.sheet_w(pass_name)}×{spec.sheet_h(pass_name)} px",
                f"baseline y={spec.baseline_y(pass_name)}",
            ]
            if stat:
                meta_bits.append(f"colors {stat['colors']}")
                meta_bits.append(f"alpha0 {stat['alpha0_pct']}%")
            parts.append(f"<div class=\"meta\">{' · '.join(html.escape(b) for b in meta_bits)}</div>")

            if zoom.exists():
                parts.append(f"<a href=\"{html.escape(_href_for(rt, anchor))}\"><img src=\"{html.escape(_href_for(zoom, anchor))}\" alt=\"{character} {pass_name} 4× zoom\"></a>")
            elif rt.exists():
                parts.append(f"<a href=\"{html.escape(_href_for(rt, anchor))}\"><img src=\"{html.escape(_href_for(rt, anchor))}\" alt=\"{character} {pass_name}\" style=\"image-rendering: pixelated; transform: scale(2); transform-origin: top left;\"></a>")

            # GIFs
            gif_paths = sorted(spec.preview_dir().glob(f"{spec.name}_{pass_name}_*.gif"))
            if gif_paths:
                parts.append("<div class=\"gifs\">")
                for g in gif_paths:
                    label = g.stem.removeprefix(f"{spec.name}_{pass_name}_")
                    parts.append(f"<figure><img src=\"{html.escape(_href_for(g, anchor))}\" alt=\"{label}\"><figcaption>{html.escape(label)}</figcaption></figure>")
                parts.append("</div>")

            parts.append("</div>")
        parts.append("</div></section>")

    parts.append("<footer>tools/sprites/catalog.py — re-run to refresh after new conversions</footer>")
    parts.append("</body></html>")
    out_path.write_text("\n".join(parts))

    header("catalog")
    print(green("wrote   ") + relpath(out_path))
    print(dim(f"open in a browser: file://{out_path}"))
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
